### ISSUE TITLE
Dead download links in section "Code and Data"

### ISSUE THREAD

**Issue by 99991** [karaimer/beyond-rawRGB-sRGB#1]
The following two links in the section "Code and Data" return error code 404 Not Found.

* https://drive.switch.ch/index.php/s/outyVAruHJe2c1P
* https://drive.switch.ch/index.php/s/viGq6d0WKtCgF3V

They are declared here:

https://github.com/karaimer/beyond-rawRGB-sRGB/blob/3fddce7b254be3a6d2da0c2b7e7f344ffbfbdcfc/index.md?plain=1#L17

**Comment by karaimer** [comment]
Just saw this issue, I'll fix it soon.

**Comment by karaimer** [comment]
I've just updated the links to download code and data as well as the readme file. Thank you for letting me know about this issue. I appreciate it.
